scoreboard:
  enabled: true
  ticks: 20
  title: '&l&k[&r&6&lWorldFall&r&l&k]&r'
  text:
    - "&6Player: &a%player_name%"
    - ""
    - "&6X: &a%coord_x%"
    - "&6Y: &a%coord_y%"
    - "&6Z: &a%coord_z%"
    - "&6Status: &a%wf_status%"